### ISSUE TITLE
关于邮箱账号

### ISSUE THREAD

**Issue by UZIhuhuhu** [Wonz5130/NJUPT-Yellow-Page#3]
每一届的邮箱密码都是不一样的，比如 18 级的邮箱密码是 Nj 什么什么的，具体的密码如果忘记了还是得问辅导员。（：

**Comment by Wonz5130** [comment]
多谢提醒~

**Comment by Wonz5130** [comment]
> 每一届的邮箱密码都是不一样的，比如 18 级的邮箱密码是 Nj 什么什么的，具体的密码如果忘记了还是得问辅导员。（：

多谢提醒~
