### ISSUE TITLE
About the latest Online Judge

### ISSUE THREAD

**Issue by ZsgsDesign** [Wonz5130/NJUPT-Yellow-Page#4]
This is a meaningful project and you may try using Wiki for it, it's more convenient if the database gets larger in the future.

The latest NOJ is still under its development and has access limited to ACM team and a few others only 'cause it's **highly unstable and may encounter errors all the time**. So I do not recommend students using this version `http://10.166.31.25` as their training platform. The future version, which may be stabilized and open to the public would be deployed to `https://icpc.njupt.edu.cn` as planned. And I believe at that time it would be more appropriate to share it to the internet. 

By the way, NOJ is an open-source project located [here](https://github.com/ZsgsDesign/CodeMaster), if anyone has an interest, please leave a message to me.

**Comment by Wonz5130** [comment]
> This is a meaningful project and you may try using Wiki for it, it's more convenient if the database gets larger in the future.
> 
> The latest NOJ is still under its development and has access limited to ACM team and a few others only 'cause it's **highly unstable and may encounter errors all the time**. So I do not recommend students using this version `http://10.166.31.25` as their training platform. The future version, which may be stabilized and open to the public would be deployed to `https://icpc.njupt.edu.cn` as planned. And I believe at that time it would be more appropriate to share it to the internet.
> 
> By the way, NOJ is an open-source project located [here](https://github.com/ZsgsDesign/CodeMaster), if anyone has an interest, please leave a message to me.

Thanks, Boss Zhang.
