### ISSUE TITLE
来自SEUITE的问候！

### ISSUE THREAD

**Issue by SEUITE-Susan** [Wonz5130/NJUPT-Yellow-Page#8]
Susan过来玩啦！感谢南京邮电大学的同学们为开源社区做出的贡献！Susan也非常欢迎南邮的同学们来Susan这边玩哦~（[硬广](https://github.com/seuite/awesome-seu)（逃

Susan发现写issue好困难哦，能不能提供一个issue的模板以方便同学们更快更轻松的将自己的或者自己朋友的或者自己同学的或者自己老师的或者自己知道的或者自己不知道的项目分享给大家呢~

Template可以在repo的settings里面创建，或者直接提交ISSUE_TEMPLATE.md到目录下就可以啦~
（当然你也可以参考Susan自己写的Template哟（硬广（逃

最后，希望南京邮电大学的开源社区能够一直和平友好，快乐前(mo)进(yu)！

SEU-ITE
Susan
2019/6/1

> 顺便祝南邮的同学们儿童节快乐！

**Comment by Wonz5130** [comment]
> Susan过来玩啦！感谢南京邮电大学的同学们为开源社区做出的贡献！Susan也非常欢迎南邮的同学们来Susan这边玩哦~（[硬广](https://github.com/seuite/awesome-seu)（逃
> 
> Susan发现写issue好困难哦，能不能提供一个issue的模板以方便同学们更快更轻松的将自己的或者自己朋友的或者自己同学的或者自己老师的或者自己知道的或者自己不知道的项目分享给大家呢~
> 
> Template可以在repo的settings里面创建，或者直接提交ISSUE_TEMPLATE.md到目录下就可以啦~
> （当然你也可以参考Susan自己写的Template哟（硬广（逃
> 
> 最后，希望南京邮电大学的开源社区能够一直和平友好，快乐前(mo)进(yu)！
> 
> SEU-ITE
> Susan
> 2019/6/1
> 
> > 顺便祝南邮的同学们儿童节快乐！

谢谢 Susan 的建议以及儿童节祝福~

Issue 模板已用 Susan 的，非常给力，赞👍

> 同希望东南大学的开源社区越来越好，一起快乐前(mo)进(yu)！
> 
> 顺便同祝东南大学的小伙伴们儿童节快乐🍭永远年轻😋
